# Generated by Django 5.1.3 on 2025-02-08 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('age', models.PositiveSmallIntegerField(verbose_name='سن')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='ملیت')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
            ],
            options={
                'verbose_name': 'ناشر',
                'verbose_name_plural': 'ناشران',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('publication_date', models.DateField(verbose_name='تاریخ انتشار')),
                ('isbn', models.CharField(max_length=13, verbose_name='شابک')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('pages', models.PositiveBigIntegerField(verbose_name='تعداد صفحات')),
                ('cover_image', models.FileField(blank=True, null=True, upload_to='book/covers', verbose_name='تصویر جلد')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.author', verbose_name='نویسنده')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.publisher', verbose_name='ناشر')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب ها',
            },
        ),
    ]
